on: [push]

name: build

env:
  OPENSSL_ENC_KEY: ${{ secrets.OPENSSL_ENC_KEY }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check system
        run: |
          lscpu && free -h
          openssl version
          bash scripts/a.sh

      - name: Read archive
        run: |
          bash scripts/unarchive.sh
        
      - name: Run tests
        run: |
          cd balancer_v2
          bash scripts/build_in_centos7.sh